name: QuestWeaver
version: '${version}'
main: br.dev.projetoc14.QuestWeaver
api-version: '1.21'

# Especificando comandos
commands:
  help:
    description: "Comandos básicos do plugin QuestWeaver"
  startmatch:
    description: "Inicia jogo mesmo que não contenha nenhum jogador."
    usage: /startmatch
    permission: questweaver.plugin.startmatch