name: QuestWeaver
version: '${version}'
main: br.dev.projetoc14.QuestWeaver
api-version: '1.21'
author: GrupoC14

# Especificando comandos
commands:
  help:
    description: "Comandos básicos do plugin QuestWeaver"
  resetclass:
    description: Reseta a Classe